requirejs([
    // "../libs/jquery/jquery.min",
    // "../libs/jquery-ui/jquery-ui.min",
    // "../libs/howler.min",
    // "../libs/underscore-min",
    // "../libs/pathfinding-browser.min",
    "src/game/Game",
    "src/game/controller/Controller",
    "src/game/controller/GamePad",
    "src/game/controller/Keyboard",
    "src/game/game/GameManager",
    "src/game/game/MapManager",
    "src/game/game/Pathfinding",
    "src/game/game/Player",
    "src/game/game/box/Box",
    "src/game/game/box/BoxManager",
    "src/game/game/component/Move",
    "src/game/game/component/Undoredo",
    "src/game/game/enemy/Enemy",
    "src/game/game/enemy/EnemyManager",
    "src/game/server/Account",
    "src/game/server/ServerConfig",
    "src/game/ui/About",
    "src/game/ui/AccountCreated",
    "src/game/ui/EndGameScreen",
    "src/game/ui/GameScreen",
    "src/game/ui/GameStage",
    "src/game/ui/GoodPassword",
    "src/game/ui/Help",
    "src/game/ui/HighScore",
    "src/game/ui/LevelSelect",
    "src/game/ui/LoadScreen",
    "src/game/ui/Login",
    "src/game/ui/Menu",
    "src/game/ui/NeedPasswordAndLogin",
    "src/game/ui/Options",
    "src/game/ui/UIManager",
    "src/game/ui/WrongPassword",
    "src/utils/Config",
    "src/utils/assetsmanager/Animation",
    "src/utils/assetsmanager/AnimationList",
    "src/utils/assetsmanager/AnimationManager",
    "src/utils/assetsmanager/SoundManager",
    "src/utils/assetsmanager/SpriteManager",
    "src/utils/debug/Debug",
    "src/utils/debug/Stats",
    "src/utils/display/GameContainer",
    "src/utils/game/GameEffect",
    "src/utils/game/Time",
    "src/utils/loader/LoaderManager",
    "src/utils/loader/PreLoad",
    "src/utils/loader/SoundLoader",
    "src/utils/loader/SpriteLoader",
    "src/utils/localization/txt",
    "src/utils/math/Vector2"
], function(Game) {
    //This function is called when scripts/helper/util.js is loaded.
    //If util.js calls define(), then this function is not fired until
    //util's dependencies have loaded, and the util argument will hold
    //the module value for "helper/util".
    Game.init();
});
